import React from 'react';

const HomePage: React.FC = () => {
    return (
        <div>
            <h1 className="center">Welcome to Home, Bro!</h1>
            <p>This is the homepage.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet animi, aspernatur earum eius error est facilis hic id incidunt ipsum libero maiores minima molestiae molestias non, odio officiis quae quaerat quidem recusandae reiciendis soluta tempora unde voluptate. Ab accusamus alias aliquam atque beatae commodi debitis dicta, doloremque dolores eaque eos et eveniet ex expedita fuga fugiat harum incidunt ipsum labore laboriosam laborum magnam maxime minus molestias neque nesciunt nihil officia ratione reiciendis repudiandae rerum sapiente temporibus tenetur veritatis vero vitae voluptate! Adipisci aliquam aspernatur autem consequatur corporis culpa dicta dignissimos eligendi est eum ex fuga hic impedit ipsa ipsam iste iusto libero magni nam necessitatibus nesciunt nisi nostrum nulla obcaecati optio porro praesentium quia quibusdam quo, ratione recusandae sapiente similique sunt unde ut voluptas voluptatem. Ad adipisci animi assumenda autem blanditiis consequuntur distinctio dolor dolorem enim eveniet explicabo fugiat impedit ipsum iusto, nam nulla omnis quis unde vero voluptates? Ad blanditiis error incidunt ipsum libero nemo neque nesciunt numquam pariatur, qui quisquam quo sunt tenetur! Ab dolorum harum illum optio quo quod ut. Accusamus ea esse exercitationem facere hic illo, mollitia nulla, provident quibusdam sunt temporibus voluptate. Dicta eligendi ipsa sit? Accusamus aliquid amet asperiores aspernatur aut, consectetur consequuntur cum debitis dicta dignissimos dolor eaque enim error est eveniet excepturi fugiat illo ipsa maiores mollitia nesciunt nihil nulla officia pariatur placeat praesentium quaerat ratione repellendus reprehenderit rerum saepe similique tempora totam, ullam vitae voluptas voluptates. A ad asperiores assumenda autem dolorem doloremque ducimus ea, eveniet incidunt laudantium libero natus nisi numquam omnis, porro praesentium provident quam quo reiciendis reprehenderit sapiente sed ullam ut? Harum, omnis, rem. Ad ex labore laudantium, magnam minima provident sequi. Ad amet aut autem corporis culpa dolore dolorum ea eius enim et eveniet in incidunt inventore ipsum iste, libero maiores nesciunt obcaecati possimus reprehenderit saepe sapiente sit soluta temporibus vel velit vitae voluptates. Accusamus beatae deserunt, eos ex expedita impedit minima molestiae rerum ut voluptatum. Accusantium alias animi asperiores cupiditate dignissimos expedita harum id nihil quaerat qui, repudiandae sequi, tenetur vero? A aliquam aliquid animi architecto asperiores assumenda, autem cumque enim facere iste magnam maiores nam optio pariatur, repellendus rerum sequi, voluptatum. Architecto cum enim esse fuga harum illum quae soluta. Animi architecto asperiores at cupiditate dicta dolore facere hic mollitia nihil nostrum sapiente tempora, ullam, voluptatibus! Debitis dolores molestias quae quam, quas quasi quisquam. Asperiores at consectetur eaque inventore ipsa molestias nostrum repellendus voluptatem.</p>
        </div>
    );
};

export default HomePage;